# Generated by Django 3.2.4 on 2021-07-03 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0008_auto_20210703_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pusblished_counteries',
            new_name='published_counteries',
        ),
    ]
